version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: cd ./server && npm start
    volumes:
      - /node_modules
    ports:
      - '2121:2121'
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    volumes:
      - /node_modules
    depends_on:
      - server
    ports:
      - '3000:3000'
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   data-volume: 
#   node_modules:
#   web-root:
#     driver: local
